### ISSUE TITLE
error with magic storage

### ISSUE THREAD

**Issue by LimaIndiaMikeAlfa** [Kalciphoz/kRPG#10]
I installed with magic storage and disappeared the hotbar, or when I open the chest everything disappears
![sem titul2o](https://user-images.githubusercontent.com/35153593/34632301-c1830a74-f25b-11e7-85d0-ec1591cd1e9f.jpg)
![sem titul23o](https://user-images.githubusercontent.com/35153593/34632302-c1a6d670-f25b-11e7-9e7a-77aaa74844b5.jpg)
![sem titulo](https://user-images.githubusercontent.com/35153593/34632303-c1d0c41c-f25b-11e7-9dbe-f45e1c087f28.jpg)

**Comment by Kalciphoz** [comment]
You look to be using an outdated version of my mod.
