### ISSUE TITLE
Multiplayer + other mods = lag

### ISSUE THREAD

**Issue by chidddy** [Kalciphoz/kRPG#15]
Insane lag with other mods, possibly because this mod affects so many of the items, who knows, hope there's something you can do, thanks

(Here's a picture of all my mods, cant take a pic of all so here's them in a few links)
https://i.imgur.com/g0V1D0k.png
https://i.imgur.com/vQ0WFe8.png
https://i.imgur.com/T23dApa.png

**Comment by FairfieldTekLLC** [comment]
Please grab version 2.0.5 and retest
