### ISSUE TITLE
Error spammed in chat and logs.

### ISSUE THREAD

**Issue by deltanedas** [Kalciphoz/kRPG#16]
`Silently Caught Exception: Index was outside the bounds of the array.  at Terraria.ModLoader.GlobalItem.Instance(Item item)  at Terraria.ModLoader.ModCompile.<>c.<ActivateExceptionReporting>b__15_0(Object sender, FirstChanceExceptionEventArgs exceptionArgs)`
I keep getting above in my chat and logs. If there is a C solution I can get, I'll fix it with provided code. Kalciphoz, pls fix.

> Silently Caught Exception: Index was outside the bounds of the array.  at Terraria.ModLoader.GlobalItem.Instance(Item item)  at Terraria.ModLoader.ModCompile.<>c.<ActivateExceptionReporting>b__15_0(Object sender, FirstChanceExceptionEventArgs exceptionArgs)
>   at Terraria.ModLoader.GlobalItem.Instance(Item item)
>   at Terraria.ModLoader.ItemLoader.GetGlobalItem(Item item, Type type)
>   at Terraria.Item.GetGlobalItem[T]()
>   at kRPG.kProjectile.SelectItem(Projectile projectile) in c:\Users\Cornelius\Documents\My Games\Terraria\ModLoader\Mod Sources\kRPG\kProjectile.cs:line 134
>   at kRPG.kProjectile.AI(Projectile projectile) in c:\Users\Cornelius\Documents\My Games\Terraria\ModLoader\Mod Sources\kRPG\kProjectile.cs:line 122
>   at Terraria.ModLoader.ProjectileLoader.AI(Projectile projectile)
>   at Terraria.ModLoader.ProjectileLoader.ProjectileAI(Projectile projectile)
>   at Terraria.Projectile.Update(Int32 i)
>   at Terraria.Main.DoUpdate(GameTime gameTime)
>   at Terraria.Main.Update(GameTime gameTime)
>   at Microsoft.Xna.Framework.Game.Tick()
>   at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
>   at Microsoft.Xna.Framework.GameHost.OnIdle()
>   at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
>   at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
>   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
>   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
>   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
>   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
>   at System.Windows.Forms.Application.Run(Form mainForm)
>   at Microsoft.Xna.Framework.WindowsGameHost.Run()
>   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
>   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
>   at Terraria.WindowsLaunch.Main(String[] args)

What I think is causing the error:
Lines 133 - 139: in kProjectile.cs
```
elementalDamage = new Dictionary<ELEMENT, int>()
{
{ELEMENT.FIRE, 0},
{ELEMENT.COLD, 0},
{ELEMENT.LIGHTNING, 0},
{ELEMENT.SHADOW, 0}
};
```
I think the projectile ID is not registered in the dictionary, so the array is shorter than expected, hence out of bounds.

**Comment by FairfieldTekLLC** [comment]
This is resolved in 2.0.5
