### ISSUE TITLE
Invisible Weapons When Used

### ISSUE THREAD

**Issue by Retroroid** [Kalciphoz/kRPG#17]
Some weapons with a sword-swing type animation are invisible when used. 

![Untitled](https://user-images.githubusercontent.com/51481375/65378634-ee183800-dc80-11e9-818a-9ec6128e5235.png)

Mod List:

Kalciphoz's RPG Mod v1.2.1
Terraria Overhaul v 4.0.4.1
Base Mod v1.9.0.1
Furniture, Food, and Fun v1.7.3.3
imkSushi Name Pack v0.2.0
imkSushi Death Counters v1.1.1
imkSushi Data Packs v1.0.1
imkSushi's Mod v4.3.1
Magic Storage v0.4.3.4
Magic Fertilizer v0.1
Helpful Hotkeys v1.6.1
Recipe Browser v0.8.3.2
OmniSwing v2.1
Auto Trash v0.4
Wing Slot v1.6.3
Shorter Respawn Time v1.0
Dual Wielding v1.0
Monster Girl Enemies v0.2
Prefixes For Enemies v2.0.0
Solution Mod v1.4.1
Even More Modifiers v0.1.2.3
WeaponOut v1.6.4
Item Checklist v0.5.2
Boss Checklist v0.2.1

**Comment by FairfieldTekLLC** [comment]
I have no way to know if this is due to kRPG.  I have not seen this issue with the current build.
I am thinking it might have to do with other mods.
