### ISSUE TITLE
Magic Storage - Compatibility issue

### ISSUE THREAD

**Issue by Tzucaza** [Kalciphoz/kRPG#27]
What mods are needed to reproduce the issue:
-Krpg
-Magic Storage

What happens:
If you try to open the Magic Storage Interface nothing happens (it doesnt open).

Error Log:
The game doesnt Crash and nothing shows up in the Logs

**Comment by FairfieldTekLLC** [comment]
I haven't forgotten about it, just haven't had a chance to look into it.

**Comment by FairfieldTekLLC** [comment]
Ok, magic storage now works.... enjoy
