### ISSUE TITLE
Procedural Spear appearance not syncing with other clients

### ISSUE THREAD

**Issue by TNTftw21** [Kalciphoz/kRPG#31]
Now that everything is (mostly) working, I'm giving kRPG a try with some friends. One issue that cropped up is that the procedural spears are not displaying properly. Specifically, when connected to a server and a client uses the spear, the other clients will not display the spear being used properly ([capture](https://user-images.githubusercontent.com/7863958/74489891-6380e100-4e8c-11ea-99dc-79ca1f03bcbb.png)). Additionally, the other clients' chat will be populated with an exception ([client.log](https://github.com/Kalciphoz/kRPG/files/4202030/client.log)).

**Comment by FairfieldTekLLC** [comment]
This is fixed with 2.0.13
