### ISSUE TITLE
Enemies with "Shimmering" prefix teleport in Multiplayer

### ISSUE THREAD

**Issue by TNTftw21** [Kalciphoz/kRPG#32]
In Multiplayer, enemies that have the "Shimmering" prefix, upon being hit, will disappear for a seemingly random amount of time. They can be forced to reappear _if_ the player takes damage from them, but otherwise they remain invisible. The player is totally unable to hit them during this period (presumably because handling whether or not the player hits an NPC is done by the client). [client.log](https://github.com/Kalciphoz/kRPG/files/4202149/client.log) is linked, of note is an error when handling 
PrefixNPC, although it happens rarely and may not necessarily be related. I've seen this bug occur with only kRPG enabled, although the client.log attached is from a session with multiple mods loaded.

**Comment by TNTftw21** [comment]
As of the latest commit (52db888), the issue still does not appear to be resolved. In point of fact, now enemies that _don't_ have the Shimmering prefix are desyncing. As well, it appears as though enemies no longer spawn properly in Singleplayer (you can occasionally hear a zombie growl, for example, but it never appears on screen). Neither the client nor the server or throwing errors, however the relevant logs are attached.

[client.log](https://github.com/Kalciphoz/kRPG/files/4206966/client.log)
[server.log](https://github.com/Kalciphoz/kRPG/files/4206967/server.log)

---EDIT---
Ope, forgot the client log for SP where enemies weren't spawning. Attached via [pastebin](https://pastebin.com/4JykCUpd) because in this case it was more convenient.

**Comment by TNTftw21** [comment]
Reproduced issue while hosting locally on my personal Windows machine as well as remotely on an old Linux box, teleportation doesn't seem to be tied to Shimmering enemies anymore. It seems now that the only enemies who do it don't have a prefix at all (that is to say that the enemies who teleport don't have prefixes, not that ALL enemies that don't have prefixes teleport).

Interestingly, the issue could be reproduced on a remote "server" (just an older machine I have that runs Linux), but could *not* be reproduced on a true server.

Client/server logs from local reproduction:
[client.log](https://github.com/Kalciphoz/kRPG/files/4207570/client.log)
[server.log](https://github.com/Kalciphoz/kRPG/files/4207571/server.log)

**Comment by FairfieldTekLLC** [comment]
This whole mess is resolved now, originally Kal initialized the mob in the PostAI, I moved all the initialization into SetDefaults for NPC.  Magically all the desync issues went away.
