### ISSUE TITLE
Incompatibility with Magic Storage mod.

### ISSUE THREAD

**Issue by Nordblum** [Kalciphoz/kRPG#4]
When trying to interact with any of Magic Storage's interfaces (i.e. Storage Heart), the interface just doesn't show up at all.
This one hurts real bad, considering the amount of loot this mod provides.

**Comment by Nextshot** [comment]
Does the Dungeon guardian drops something for Magic Storage mod ? I was a fresh spawn, when I killed it and collected the drops the game crashed, I tried 3 times and crashed all of them.
I will make some tests on sandbox mode.
