### ISSUE TITLE
No EXP, Nurse keeps throwing bones

### ISSUE THREAD

**Issue by bhcarpenter-fun** [Kalciphoz/kRPG#45]
Hello,

I am currently running Calamity, Boss Checklist, Fargo's Mutant and Soul mods, Reduced Grinding, Upgraded Accessories, and Wingslot. Everything was working fine until the new 2.0.17 update that came out today. Now, I get no EXP from killing enemies, the Spell Skull can't be accessed, and my Nurse is endlessly attacking the air. I've tried to revert to 2.0.15, but I can't get the mod zip to load in tMod. Do you have any way to fix this or at least tell me how to load the older version from the zip file?

Thanks.

**Comment by FairfieldTekLLC** [comment]
Please update and try 2.0.23
