### ISSUE TITLE
Issues with auto-consume pickups

### ISSUE THREAD

**Issue by Shahelion** [Kalciphoz/kRPG#6]
Only two I know of so far are both from Thorium. They aren't ever supposed to actually be in the inventory.

Inspiration Notes work like Mana Stars or Hearts but for the Bard Class's Inspiration system.

Also the shadows that are used to summon Abyssion (auto-summons once a player picks up three).

**Comment by FairfieldTekLLC** [comment]
Please provide more information, assume I know nothing.  So, if this is a issue w/ regards to another mod, please post the name of the other mod, screen shots etc.
