### ISSUE TITLE
Items aren't being picked up when they should be

### ISSUE THREAD

**Issue by Shahelion** [Kalciphoz/kRPG#8]
If the main inventory is full, it blocks the pickup of things that already have another slot with that item, like arrows in the ammo slot or mana stars. Makes no sense.

**Comment by FairfieldTekLLC** [comment]
I believe this is a issue with the custom inventory.  I'll make a pass at it next.

**Comment by FairfieldTekLLC** [comment]
This appears to be fixed when it comes to looting dropped items.  For items in a chest, you need to go to an inventory page that has empty slots to loot all
